### ISSUE TITLE
Support code splitting

### ISSUE THREAD

**Issue by gregorskii** [taviroquai/ReactObservableStore#3]
See #2

**Comment by taviroquai** [comment]
Looks nice!

Some questions:
 
1. where do you use the add() ? After import?
2. How do you use? I see that you call sanitizeData(data[namespace]) so the data must be in the format:
```
{
  namespace: {
    prop: true
  }
}
```

Assumming that the data only belongs to that namespace, wouldn't make more sense being just the namespace data? Ie.
```
Store.add('namespace', {
  prop: true
})
```

Cheers

**Comment by gregorskii** [comment]
@taviroquai I set it up to use the add in another entry point of webpack. The main webpack entrypoint does the init, the others add new keys.

I used the same syntax for consistency, it could be either way, but it seemed more consistent to define the initial state the same way.

On my project we are importing the initial state from a file called store.js, as that way it can also be imported on a reducer like file inside an observable container component to be used on a reset like action. Store.js is imported by the entry file, and each store an entry defines by add is imported using the destructured import syntax.

Example:

store.js:

```
export const a = {
   a: {}
}

export const b = {
   b: {}
}
```

Entry 2:

```
import { a, b } from ‘./store.js’

Store.add(‘a’, a)
Store.add(‘b’, b)
```

This way the key for the store is also in the store.js file for reference.

**Comment by taviroquai** [comment]
@gregorskii Ahh now I see why you use that structure, for dynamic referencing :)

The difference that I see is that, logically, the initial state holds **all** the namespaces, while the add interface is for a **single** namespace.

Using the same dymanic reference approach, would this work for you?

**Entry 2:**
```
import { a, b } from ‘./store.js’
Store.add('a', a['a'])
Store.add('b', b['b'])
```

**Comment by gregorskii** [comment]
You could do this yes, but on our project the initial data could be quite large and page specific. We are using our entry points for code splitting, so it makes sense for us to only define the store for entry B in a store file imported by entry B.

Though we could accomplish this pattern if it worked generally for this project by defining an array in each entry’s store file. Essentially I could make that pattern work. :)

**Comment by gregorskii** [comment]
Oh also for the future dev trying to accomplish code splitter stores; another implantation detail that’s needed to accomplish code splitting is to make the store imported by this library attach to the window.

On the first entry where the store is initialized I set the store as a global using global.Store = Store.

**Comment by taviroquai** [comment]
@gregorskii Ok I see what you mean and I understand the advantage of using that pattern for consistency.

But I still don't feel right the add interface that accepts **one namespace** as a required parameter, but then, the second parameter is an object that can hold **N namespaces**... its counter-intuitive!

Unless, we make the add interface to load N namespaces, ie:
```
Store.add({
  ns1: { foo: true },
  ns2: { bar: true }
});
```
... in which, would also support the pattern that you are using.

**Comment by gregorskii** [comment]
I think you should do what you feel is right for the general use of the project, I can adapt my use of it to suit my project, so I have no preference.

:)

If you want me to update the pattern in this PR to match what we are discussing I can do that too.

Just wanted to clarify I’m not too picky.

**Comment by taviroquai** [comment]
@gregorskii I'm going to accept the PR beacuse this is the beaty of OpenSource, to share ideas, to collab, and most important to grow projects, even if some features don't serve the needs of everybody.

Later for version 2, we can recicle features that are not so important and improve another features like this one. Thanks and keep up the good work ;)

**Comment by gregorskii** [comment]
Awesome thank you 🙏
